-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["bully-2-iPad"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   -16, 90  ,  23, 52  ,  18, 103  ,  -16, 111  ,  -27, 107  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   -24, 50  ,  10, -40  ,  23, 52  ,  -16, 90  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   24, -70  ,  -35, -15  ,  -64, -44  ,  -64, -94  ,  -33, -109  ,  24, -105  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   41, 39  ,  23, 52  ,  10, -40  ,  43, -9  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   24, -70  ,  10, -40  ,  -43, 47  ,  -35, -15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   -43, 47  ,  10, -40  ,  -24, 50  }
                    }
                    
                    
                    
		}
		
		, 
		["patriot-2-iPad"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65533, groupIndex = 0 },
                    shape = {   -75, 100  ,  -75, 71  ,  -43, 53  ,  -33, 96  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65533, groupIndex = 0 },
                    shape = {   -60, -105  ,  -11, -72  ,  -1, -45  ,  -32, -3  ,  -84, 42  ,  -133, 23  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65533, groupIndex = 0 },
                    shape = {   -11, -72  ,  -4, -101  ,  0, -112  ,  6, -90  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65533, groupIndex = 0 },
                    shape = {   -60, -105  ,  -92, -50  ,  -104, -77  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65533, groupIndex = 0 },
                    shape = {   -84, 42  ,  -32, -3  ,  -43, 53  ,  -75, 71  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65533, groupIndex = 0 },
                    shape = {   -43, 53  ,  -32, -3  ,  -19, 47  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 65533, groupIndex = 0 },
                    shape = {   -4, -101  ,  -11, -72  ,  -60, -105  ,  -12, -113  }
                    }
                    
                    
                    
		}
		
		, 
		["spitball-iPad"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 20, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    radius = 11.045
                    }
                    
                    
		}
		
		, 
		["officerray-2-iPad"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   -20, -2.5  ,  16, -27.5  ,  35, 35.5  ,  -13, 61.5  ,  -35, 37.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   -13, 61.5  ,  35, 35.5  ,  23, 104.5  ,  10, 105.5  ,  -12, 105.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   1, -109.5  ,  39, -92.5  ,  47, -69.5  ,  16, -27.5  ,  -20, -2.5  ,  -53, -42.5  ,  -53, -82.5  }
                    }
                    
                    
                    
		}
		
		, 
		["clock-iPad"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   -15, 25  ,  -15, -22  ,  -10, -42  ,  22, -58  ,  14, 55  ,  -12, 52  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   22, -58  ,  -10, -42  ,  -25, -57  }
                    }
                    
                    
                    
		}
		
		, 
		["imbriale-2-iPad"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   0, -106  ,  29, -78  ,  16, -28  ,  -20, -11  ,  -49, -36  ,  -52, -70  ,  -43, -101  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   36, 32  ,  -16, 53  ,  -35, 38  ,  -20, -11  ,  16, -28  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 50, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   -11, 106  ,  -22, 104  ,  -16, 53  ,  36, 32  ,  22, 106  }
                    }
                    
                    
                    
		}
		
		, 
		["book-iPad"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 10, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   -6, -59  ,  31, -39  ,  57, 18  ,  -13, 8  ,  -55, -23  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 1, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65534, groupIndex = 0 },
                    shape = {   10, 59  ,  -6, 31  ,  -13, 8  ,  57, 18  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

